spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis?useUnicode=yes
    username: root
    password: 123456

  ## 先关掉spring session
  session:
    store-type: none
  ## 文件上传
  http:
    multipart:
      ## 单个文件的最大值
      max-file-size: 10MB
      ## 上传文件总的最大值
      max-request-size: 10MB

## 关闭spring security安全认证，2.0之后不再使用
#security:
#  basic:
#    enabled: false
security:
  user:
    name: admin
    password: 123456
