spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.32.145:3306/mybatis?useUnicode=yes
    username: root
    password: 123456

  ## 先关掉spring session
  session:
    store-type: none
  ## 文件上传
  http:
    multipart:
      ## 单个文件的最大值
      max-file-size: 10MB
      ## 上传文件总的最大值
      max-request-size: 10MB

## 关闭spring security安全认证，2.0之后不再使用
#security:
#  basic:
#    enabled: false

imooc:
  security:
    browser:
#      loginPage: /demo-signIn.html
      loginType: JSON
    code:
      image:
        length: 4
#        width: 100
        ## 多请求过滤
#        url: /user,/user/*
